language: python

python:
  - "3.9"
env:
  - SECRET_KEY='TEST'
services:
  - postgresql
install:
  - pip install -r requirements.txt
script:
  - coverage run --source='core' manage.py test && coverage report && coverage html
after_success:
  - codecov
