language: python

python:
  - "3.9"
env:
  - SECRET_KEY='django-insecure-du(p)yc#(_#-r@fv8b3rl8w0#7tpk@!lv$*t%f8f9##+5#g740'
  - DEBUG=True
services:
  - postgresql
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
